// EasyDeutsch (owner, 2026-09-28): German only. A German title (on screen, in the
// caption of the post) and a German hook (said and shown in the first seconds) for
// every unit of the course, in the order of lib/german-a1.mjs.
import { GERMAN_A1 } from "./german-a1.mjs";

const T = [
  ["Hallo & Tschüss", "So grüßt man auf Deutsch!"],
  ["Du oder Sie?", "Wie stellst du dich vor?"],
  ["Danke & Bitte", "Höflich sein – so einfach!"],
  ["Zahlen von 0 bis 5", "Zähl mit mir!"],
  ["Zahlen von 6 bis 10", "Weiter geht's mit dem Zählen!"],
  ["Die Familie", "Wer gehört zur Familie?"],
  ["Fragewörter", "Was? Wo? Wann? Wie?"],
  ["Das Verb „sein“", "Ich bin, du bist – so geht's!"],
  ["Farben", "Welche Farbe siehst du?"],
  ["Die Wochentage", "Welcher Tag ist heute?"],
  ["Die Uhrzeit", "Wie spät ist es?"],
  ["Das Verb „haben“", "Ich habe, du hast – hör zu!"],
  ["Essen und Trinken", "Was isst und trinkst du?"],
  ["Im Café", "So bestellst du im Café!"],
  ["Zahlen von 11 bis 20", "Noch mehr Zahlen!"],
  ["Das Wetter", "Wie ist das Wetter heute?"],
  ["Adjektive", "Groß, klein, schnell, langsam!"],
  ["Einkaufen", "Was kostet das?"],
  ["Nach dem Weg fragen", "Wo ist der Bahnhof?"],
  ["Länder und Sprachen", "Woher kommst du?"],
  ["Berufe", "Was bist du von Beruf?"],
  ["Mein Tag", "So sieht mein Tag aus!"],
  ["Wichtige Verben", "Gehen, kommen, machen, sehen!"],
  ["Kleidung", "Was ziehst du an?"],
  ["Können", "Was kannst du gut?"],
  ["Zu Hause", "Wo wohnst du?"],
  ["Am Bahnhof", "Wann fährt der Zug?"],
  ["Fahrkarten kaufen", "Eine Fahrkarte, bitte!"],
  ["Einen Termin machen", "Haben Sie heute Zeit?"],
  ["Beim Arzt", "Ich brauche einen Arzt!"],
  ["Small Talk", "Wie geht es Ihnen?"],
  ["Buchstabieren", "Wie schreibt man das?"],
  ["Bezahlen", "Bar oder mit Karte?"],
  ["Der Akkusativ", "Ich sehe den Mann!"],
  ["Trennbare Verben", "Ich rufe dich an!"],
  ["Freizeit", "Was machst du gern?"],
  ["Das Pfand", "Flasche zurück, Geld zurück!"],
  ["Wichtige Nummern", "Wie ist deine Telefonnummer?"],
  ["Die Adresse", "Wie ist Ihre Adresse?"],
  ["Auf dem Amt", "Ich habe einen Termin."],
  ["Was ist das?", "Das ist ein Stuhl!"],
  ["Wem gehört das?", "Das ist mein Schlüssel!"],
  ["Nein sagen: kein & nicht", "Kein Geld? Keine Zeit? So sagst du es!"],
  ["Möbel", "Sofa, Tisch, Bett – wie heißt das?"],
  ["Die Tageszeiten", "Morgen, Mittag, Abend, Nacht"],
  ["Das Wochenende", "Was machst du am Samstag?"],
  ["Pläne machen", "Hast du morgen Zeit?"],
  ["Zu spät kommen", "Entschuldigung, ich komme zu spät!"],
  ["Traumberufe", "Was möchtest du werden?"],
  ["Im Gebäude", "Wo ist der Aufzug?"],
  ["Den Weg beschreiben", "An der Ampel links!"],
  ["Lebensmittel", "Brot, Milch, Käse, Eier"],
  ["An der Theke", "Was darf es sein?"],
  ["Ein Ausflug", "Wir machen einen Ausflug!"],
  ["Der Wetterbericht", "Wie wird das Wetter morgen?"],
  ["Körperteile", "Kopf, Hand, Rücken, Fuß"],
  ["Symptome", "Ich habe Fieber!"],
  ["In der Apotheke", "Haben Sie etwas gegen Kopfschmerzen?"],
  ["Perfekt mit „haben“", "Ich habe gearbeitet!"],
  ["Perfekt mit „sein“", "Ich bin nach Hause gegangen!"],
  ["„war“ und „hatte“", "Ich war schon in Berlin!"],
  ["Wo liegt das?", "Wie weit ist das?"],
  ["Länder in Europa", "Österreich, Frankreich, Polen …"],
  ["Meine Heimat", "Ich komme aus Afghanistan."],
  ["Warum bist du hier?", "Was machst du hier?"],
  ["Die Monate", "Von Januar bis Dezember"],
  ["Die Jahreszeiten", "Frühling, Sommer, Herbst, Winter"],
  ["Geburtstag", "Wann hast du Geburtstag?"],
  ["Im Restaurant", "Die Speisekarte, bitte!"],
  ["Einladen", "Ich lade dich ein!"],
  ["Gefühle", "Wie fühlst du dich?"],
  ["Eine Wohnung suchen", "Ist die Wohnung noch frei?"],
  ["Miete und Rechnungen", "Wie hoch ist die Miete?"],
  ["Bei der Bank", "Ich möchte ein Konto eröffnen."],
  ["Auf der Post", "Ich möchte ein Paket schicken."],
  ["Am Telefon", "Hallo, hier spricht Nico."],
  ["Formulare", "Vorname, Nachname, Unterschrift"],
  ["Im Deutschkurs", "Ich habe eine Frage!"],
  ["Kinder", "Ich habe zwei Kinder."],
  ["Sport", "Treibst du Sport?"],
  ["Musik und Medien", "Welche Musik magst du?"],
  ["Größen", "Welche Größe haben Sie?"],
  ["Vergleichen", "Das ist billiger!"],
  ["Müssen", "Ich muss arbeiten."],
  ["Dürfen", "Darf ich hier parken?"],
  ["Wollen", "Ich will Deutsch lernen!"],
  ["Der Imperativ", "Komm bitte her!"],
  ["Der Dativ", "Ich gebe dir das Buch."],
  ["Mein, dein, sein", "Das ist meine Wohnung!"],
  ["Wo? Auf, unter, in", "Wo liegt das Buch?"],
  ["Zeit: um, am, im", "Um acht Uhr beginnt der Kurs."],
  ["Bus und Bahn", "Wo muss ich umsteigen?"],
  ["Taxi und Auto", "Zum Hauptbahnhof, bitte!"],
  ["Im Hotel", "Ich habe ein Zimmer reserviert."],
  ["Notfall", "Hilfe! Rufen Sie einen Arzt!"],
  ["Das Fundbüro", "Ich habe meine Tasche verloren."],
  ["Nachbarn", "Ich bin neu hier."],
  ["Das Vorstellungsgespräch", "Ich habe drei Jahre Erfahrung."],
  ["Der Arbeitstag", "Ich mache Feierabend!"],
  ["Rückblick A1", "Was hast du schon gelernt?"],
];

export const EASY_TEXT = Object.fromEntries(GERMAN_A1.map((u, i) => [u.id, { title: T[i]?.[0], hook: T[i]?.[1] }]));
export const EASY_TITLE_COUNT = T.length;
